version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "praktikum"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      # PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"

    hostname: postgres
    network_mode: bridge 
    # volumes:
    #   - pg-data:/var/lib/postgresql/data
# volumes:
#   pg-data: